FROM node:24-alpine

# Install database clients needed for backups
RUN apk add --no-cache \
    mysql-client \
    mariadb-connector-c \
    postgresql-client \
    tzdata

WORKDIR /app
COPY package*.json ./
RUN npm install --includes=dev
COPY . .

CMD ["npm", "run", "dev"]