services:
  services-backup:
    image: ghcr.io/hugoheml/services-backup:v1.0.0-beta.6
    environment:
      - BACKUP_PTERODACTYL=true
      - PTERODACTYL_URL=<PTERODACTYL_URL>
      - PTERODACTYL_API_KEY=<PTERODACTYL_API_KEY>
      - PTERODACTYL_FETCH_AS_ADMIN=true
      - PTERODACTYL_FOLDER_PATH=/pterodactyl/servers
      
      - BACKUP_MYSQL=true
      - MYSQL_HOST=<MYSQL_HOST>
      - MYSQL_PORT=<MYSQL_PORT>
      - MYSQL_USER=<MYSQL_USER>
      - MYSQL_PASSWORD=<MYSQL_PASSWORD>
      - MYSQL_POOL_SIZE=5
      - MYSQL_IGNORE_DATABASES=information_schema,performance_schema,mysql,sys
      - MYSQL_FOLDER_PATH=mysql
      - MYSQL_SSL_ENABLED=false

      - BACKUP_POSTGRESQL=false
      - POSTGRES_HOST=<POSTGRES_HOST>
      - POSTGRES_PORT=<POSTGRES_PORT>
      - POSTGRES_USER=<POSTGRES_USER>
      - POSTGRES_PASSWORD=<POSTGRES_PASSWORD>
      - POSTGRES_IGNORE_DATABASES=template0,template1
      - POSTGRES_FOLDER_PATH=postgresql
      - POSTGRES_SSL_ENABLED=false
      - POSTGRES_SSL_REJECT_UNAUTHORIZED=true

      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/backups
      - FTP_HOST=<FTP_HOST>
      - FTP_PORT=<FTP_PORT>
      - FTP_USER=<FTP_USER>
      - FTP_PASSWORD=<FTP_PASSWORD>

      - MAX_BACKUP_PER_ELEMENT=<MAX_BACKUP_PER_ELEMENT>
      - MAX_BACKUP_RETENTION_DAYS=<MAX_BACKUP_RETENTION_DAYS>

      - LOG_LEVEL=info
      - TMP_DIR=/tmp

      - ALERT_SERVICE_ENABLED=false

      - ALERT_DISCORD_ENABLED=false
      - DISCORD_WEBHOOK_URL=<DISCORD_WEBHOOK_URL>
    # For STORAGE_TYPE=local only
    volumes:
      - ./backups:/backups